# Generated by Django 2.2.3 on 2021-03-10 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_news_newsreader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enttype', models.CharField(default='', max_length=255)),
                ('enttext', models.CharField(default='', max_length=255)),
                ('entsenti', models.CharField(default='', max_length=255)),
                ('entsentiscore', models.FloatField(default=0.0)),
                ('entreli', models.FloatField(default=0.0)),
                ('entcount', models.FloatField(default=0.0)),
                ('entcon', models.FloatField(default=0.0)),
                ('newsreader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('newsurl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.News')),
            ],
        ),
    ]
