# Generated by Django 2.2.3 on 2021-03-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210310_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ents',
            name='newsurl',
            field=models.URLField(default='', max_length=255),
        ),
    ]
