# Generated by Django 2.2.3 on 2021-03-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210310_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ents',
            old_name='newsurl',
            new_name='enturl',
        ),
    ]
